### PR TITLE
Add unit tests to subgraph

### PR DESCRIPTION
**Pull request by yuriko627**

### CODE REVIEW

**Review by chatch — CHANGES_REQUESTED** [review]
Looks great @yuriko627. Thanks for setting up this with Typescript / Jest / Lokka etc.

One thing is the tests should be changed so they can be repeatable. Currently they are clashing on things like expected timestamps (createdAt). You mentioned this in slack about ids too right?

There are a couple of jest matchers you could try - toMatchObject and  objectContaining that let you match a subset of an object. Can you try these to filter out the createdAt properties?

Where they are random but we still want to check them we could do something like just check they are a valid address / hash / id (eg. length / hexa chars or something) OR possibly change the startrail scripts to make the values fixed instead of random. Although this might not be possible in all cases. but if you could at least identify some of these types of randomized fields that would be great - you could ignore them in the test case but leave a comment in the test script mentioned why ignored.  

the goal is to get the tests passing every time so try get that working for most fields first.

**Comment by yuriko627** [comment]
Thank you @chatch for the detail review! In the next PR, I will 
- filter out createdAt properties 
- identify fields that have randomized values and validate them (or leave a comment and ignore in the test cases)
- fix srrprovenances query order (and any other query order related issues if they exist) 

I have one question. 
For filtering out createdAt properties, instead of using partial matchers, wouldn't it be ok to just not query createdAt field leaving a comment like you suggested for the randomized value?

**Comment by chatch** [comment]
> Thank you @chatch for the detail review! In the next PR, I will
> 
>     * filter out createdAt properties
> 
>     * identify fields that have randomized values and validate them (or leave a comment and ignore in the test cases)
> 
>     * fix srrprovenances query order (and any other query order related issues if they exist)
> 
> 
> I have one question.
> For filtering out createdAt properties, instead of using partial matchers, wouldn't it be ok to just not query createdAt field leaving a comment like you suggested when ignoring randomized value?

yes i think that's fine.

**Comment by yuriko627** [comment]
@chatch I think I fixed all the points you suggested. Please take a look and try testing in your environment too. Thanks.

**Comment by chatch** [comment]
> @chatch I think I fixed all the points you suggested. Please take a look and try testing in your environment too. Thanks.

@yuriko627 all the timetamps are good now :+1: but other tests are failing in my env. there are a number differences with expected addresses and hashes. result was:
```
 FAIL  test/unit.spec.ts
  ✕ srrs (44 ms)
  ✕ licensedUserWallets  (19 ms)
  ✓ customHistoryType (9 ms)
  ✕ srrmetadataHistories (23 ms)
  ✓ metaTxRequestTypes (11 ms)
  ✕ metaTxExecutions (17 ms)
  ✕ srrprovenances (16 ms)
  ✓ srrtransferCommits (10 ms)
  ✕ bulkIssues (9 ms)
  ✓ customHistories (12 ms)
  ✓ srrHistories (12 ms)
```

do the tests pass in your env if your run 2 or more times?

if your seeing the same thing I think we need to ignore some fields in the expected results or at least check for things like isValidEthereumAddress intead of a specific address that might be different each time.  mentioned about this sort of checking in a previous comment.

the `id` fields you can completely ignore as these are hashes that include timestamp input so they will be different every time.

**Review by chatch — APPROVED** [review]
looks good - tests now passing in my local also.

**Pull request merged**
