### PR TITLE
[API 662] - Configure and deploy subgraph on thegraph.com

### PR DESCRIPTION
**Pull request by noyonthe1**

### CODE REVIEW

**Comment by noyonthe1** [comment]
> looks good.
> 
> about npm and yarn. Since yarn appears broken on mac could you delete the yarn.lock? and we'll keep this new package-lock.json instead.

ya sure!

**Comment by noyonthe1** [comment]
Done @chatch please check!

**Comment by chatch** [comment]
sorry @noyonthe1 i meant delete the yarn.lock and keep the package-lock.json! :) since npm is working in both envs.

**Comment by noyonthe1** [comment]
> sorry @noyonthe1 i meant delete the yarn.lock and keep the package-lock.json! :) since npm is working in both envs.

lol I was confused because there is no yarn.lock change set, okay let me do that! lol

**Pull request merged**
