### PR TITLE
fix srr.createdAt dates

### PR DESCRIPTION
**Pull request by chatch**
see GOGH-5444 for the original issue
see analysis on https://github.com/startbahn/startrail/pull/368

this fixes the issue by only setting createdAt on the first Transfer as it should have done

### CODE REVIEW

**Review by wshino — APPROVED** [review]

**Comment by chatch** [comment]
@wshino can this be merged? I thought this got migrated to prod yesterday? but this PR is still here...

**Comment by wshino** [comment]
@chatch yes You can merge it. Yesterday's deploy was done from this branch, sorry for that.

**Comment by wshino** [comment]
@chatch oh, wait a second...

**Comment by wshino** [comment]
@chatch Sorry, I may have deployed STARTRAIL-768 yesterday. Please let me deploy it again.

**Comment by wshino** [comment]
@chatch done, sorry for that...

**Pull request merged**
